name: Alerts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Run alerts script
      run: |
        echo "Generating alerts with Dependabot..."
        # Use the dependabot-core library to generate alerts
        npm install -g dependabot-core
        dependabot-core alerts generate
        echo "Done!"
