name: Dependabot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Trigger Dependabot
      uses: docker://dependabot/action-publish-alerts:latest
      env:
        DEPENDABOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

