name: Dependabot Updater

on:
  push:
    branches:
      - master

jobs:
  dependabot-updater:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Update dependencies
      uses: dependabot/updater-action@v2
