name: Dependabot Alert

on:
  push:
    branches:
      - master

jobs:
  update:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Update Dependencies
      uses: dependabot/updater-action@v2
