name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Dependabot
      uses: dependabot/actions/dependabot-alert@v3
      with:
        schedule-interval: 'daily'
        labels: bug,security
        auto-merge: false
        auto-merge-prefix: '[Auto merge]'
        schedule-time: '09:00'
        notify-dependents: true
        repository-dispatch: false
