name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Dependabot
      uses: docker://dependabot/dependabot-core:v1
      with:
        args: schedule
        labels: bug,security
        schedule-interval: daily
        schedule-time: 09:00
        notify-dependents: true
