name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependabot
      run: |
        npm install -g @dependabot/cli

    - name: Trigger Dependabot
      run: npx dependabot schedule --labels=bug,security --interval=daily --time=09:00
